version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    container_name: 'redis'
    restart: on-failure
    networks:
      - inpoint
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/docker_cache

  notification:
    build: ./notification_express
    container_name: 'notification'
    networks:
      - inpoint
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .files:/diskStorage

  authentication:
    build: ./authentication
    container_name: 'authentication'
    networks:
      - inpoint
    restart: on-failure
    depends_on:
      - postgres
      - redis
    volumes:
      - .files:/diskStorage

  postgres:
    image: postgres:14
    container_name: 'postgres'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
      - .files:/tmp/archive
    restart: on-failure
    networks:
      - inpoint

  gateway:
    image: nginx:alpine
    container_name: 'gateway'
    ports:
      - "3030:3030"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
      - .files:/diskStorage
    networks:
      - inpoint
    depends_on:
      - authentication
    restart: on-failure

volumes:
  db-data:
  esdata:
  cache:

networks:
  inpoint:
    driver: bridge
